In [2]:
import pandas as pd
import matplotlib as plt

In [37]:
data = pd.read_csv(r"C:\Users\singh\Desktop\DATA\Internship\yuvaintern\logistic Data Analytics\week 2\logistics_raw_data.csv")

In [40]:
data.head(10)

,Shipment_ID,Order_Date,Region,Shipping_Mode,Vehicle_Type,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating,Weather,Delivery_Status
0,SHP10000,2025-01-01,South,Road,Truck,679.9,4.87,2,3.4,4383.32,4.0,Clear,In Transit
1,SHP10001,2025-01-02,Central,Rail,Truck,521.7,4.99,1,2.7,2514.35,3.7,Rain,Cancelled
2,SHP10002,2025-01-03,West,Ship,Bike,740.9,9.20,7,8.2,7013.15,4.7,Clear,Delayed
3,SHP10003,2025-01-04,East,Air,Truck,414.4,5.24,3,4.3,1564.63,4.1,Storm,In Transit
4,SHP10004,2025-01-05,North,Ship,Truck,263.1,6.85,4,3.6,2593.65,4.0,Clear,On Time
5,SHP10005,2025-01-06,North,Rail,Container,382.5,9.43,2,2.1,3473.68,4.5,Rain,On Time
6,SHP10006,2025-01-07,North,Air,Truck,151.1,8.62,4,4.6,2612.91,3.8,Clear,In Transit
7,SHP10007,2025-01-08,Central,Ship,Container,25000.0,4.92,6,6.5,1499.52,5.0,Clear,On Time
8,SHP10008,2025-01-09,East,Road,Truck,213.8,14.59,3,3.8,2014.05,3.5,Clear,On Time
9,SHP10009,2025-01-10,West,Road,Van,881.9,10.57,4,6.4,3857.45,4.4,Clear,On Time

In [42]:
data.tail(10)

,Shipment_ID,Order_Date,Region,Shipping_Mode,Vehicle_Type,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating,Weather,Delivery_Status
1000,SHP10778,2027-02-18,West,Road,Truck,188.0,22.58,4,4.1,2035.94,4.5,Clear,In Transit
1001,SHP10334,2025-12-01,North,Ship,Truck,232.0,33.92,5,5.9,3237.62,4.1,Clear,On Time
1002,SHP10271,2025-09-29,West,Ship,Truck,217.6,3.07,3,4.2,4197.96,4.3,Clear,Delayed
1003,SHP10802,2027-03-14,East,Road,Bike,176.3,20.53,5,5.1,3490.93,3.4,Clear,On Time
1004,SHP10216,2025-08-05,South,Road,Container,408.9,7.24,2,1.9,1880.10,3.8,Clear,Cancelled
1005,SHP10408,2026-02-13,Central,Rail,Bike,603.4,8.32,4,5.8,3018.89,4.4,Clear,On Time
1006,SHP10812,2027-03-24,North,Road,Van,670.6,12.11,3,3.9,3122.10,3.0,Storm,On Time
1007,SHP10094,2025-04-05,West,Road,Truck,460.3,11.59,1,1.4,1671.08,3.0,Rain,On Time
1008,SHP10487,2026-05-03,South,Air,Bike,466.6,6.48,2,1.4,1931.31,5.0,Clear,In Transit
1009,SHP10170,2025-06-20,NaN,Rail,Van,162.6,NaN,3,4.5,1566.51,4.4,Rain,Delayed

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1010 entries, 0 to 1009
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Shipment_ID             1010 non-null   object
 1   Order_Date              1010 non-null   object
 2   Region                  997 non-null    object
 3   Shipping_Mode           999 non-null    object
 4   Vehicle_Type            1010 non-null   object
 5   Distance_km             998 non-null    float64
 6   Package_Weight_kg       997 non-null    float64
 7   Expected_Delivery_Days  1010 non-null   int64
 8   Delivery_Days           1010 non-null   float64
 9   Shipping_Cost_INR       1010 non-null   float64
 10  Delivery_Rating         998 non-null    float64
 11  Weather                 1010 non-null   object
 12  Delivery_Status         1010 non-null   object
dtypes: float64(5), int64(1), object(7)
memory usage: 102.7+ KB

In [46]:
data.describe()

,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating
count,998.000000,997.000000,1010.000000,1010.000000,1010.000000,998.000000
mean,602.607615,10.430642,3.455446,4.086139,4543.392733,3.986673
std,2425.328588,35.884765,1.583643,1.897729,32451.657976,0.598353
min,17.800000,0.620000,1.000000,0.500000,679.220000,2.200000
25%,217.800000,4.370000,2.000000,2.700000,1880.100000,3.600000
50%,359.750000,7.060000,3.000000,4.000000,2511.745000,4.000000
75%,552.425000,11.190000,4.000000,5.300000,3245.315000,4.400000
max,45000.000000,800.000000,7.000000,11.300000,800000.000000,5.000000

In [48]:
data.select_dtypes(include="object").describe()

,Shipment_ID,Order_Date,Region,Shipping_Mode,Vehicle_Type,Weather,Delivery_Status
count,1010,1010,997,999,1010,1010,1010
unique,1000,1000,8,7,4,4,4
top,SHP10170,2025-06-20,North,Road,Truck,Clear,On Time
freq,2,2,251,475,451,566,563

In [69]:
data.isnull().sum()

Shipment_ID               0
Order_Date                0
Region                    0
Shipping_Mode             0
Vehicle_Type              0
Distance_km               0
Package_Weight_kg         0
Expected_Delivery_Days    0
Delivery_Days             0
Shipping_Cost_INR         0
Delivery_Rating           0
Weather                   0
Delivery_Status           0
dtype: int64

In [ ]:
data['Region'] = data['Region'].fillna('Unknown')
data['Shipping_Mode'].fillna(method='ffill', inplace=True)
data['Distance_km'].fillna(data['Distance_km'].mean(), inplace=True)
data['Package_Weight_kg'].fillna(data['Package_Weight_kg'].median(), inplace=True)
data['Delivery_Rating'].fillna(data['Delivery_Rating'].mode()[0], inplace=True)

In [73]:
data.duplicated().sum()

np.int64(10)

In [75]:
data = data.drop_duplicates()

In [77]:
data.duplicated().sum()

np.int64(0)

In [83]:
data['Region'].unique()

array(['South', 'Central', 'West', 'East', 'North', 'Unknown', 'north',
       'West ', ' SOUTH'], dtype=object)

In [86]:
cat_cols = [
    "Region",
    "Shipping_Mode",
    "Vehicle_Type",
    "Weather",
    "Delivery_Status"
]

for col in cat_cols:
    data[col] = data[col].astype("string").str.strip().str.title()

In [88]:
data['Region'].unique()

<StringArray>
['South', 'Central', 'West', 'East', 'North', 'Unknown']
Length: 6, dtype: string

In [93]:
Q1 = data["Distance_km"].quantile(0.25)
Q3 = data["Distance_km"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = data[
    (data["Distance_km"] < lower) | (data["Distance_km"] > upper)
]

print(outliers)

    Shipment_ID  Order_Date   Region Shipping_Mode Vehicle_Type  Distance_km  \
7      SHP10007  2025-01-08  Central          Ship    Container      25000.0
65     SHP10065  2025-03-07     East           Air    Container       1327.1
70     SHP10070  2025-03-12     West          Road    Container       1112.8
84     SHP10084  2025-03-26    South          Ship          Van       1718.2
104    SHP10104  2025-04-15  Central          Ship    Container       1365.9
109    SHP10109  2025-04-20    North          Road         Bike       1165.7
110    SHP10110  2025-04-21    South          Ship        Truck       1048.1
121    SHP10121  2025-05-02  Central          Ship          Van       1490.5
193    SHP10193  2025-07-13     West          Rail          Van      25000.0
202    SHP10202  2025-07-22    North          Road        Truck       1092.1
204    SHP10204  2025-07-24     East          Road    Container       1096.6
225    SHP10225  2025-08-14    South          Rail          Van      45000.0
265    SHP10265  2025-09-23     West          Road          Van       1065.5
294    SHP10294  2025-10-22    North          Ship        Truck       2531.8
357    SHP10357  2025-12-24     East          Road        Truck       1056.9
457    SHP10457  2026-04-03     East          Rail          Van       1277.4
480    SHP10480  2026-04-26     West          Ship        Truck       1069.4
498    SHP10498  2026-05-14  Central          Road         Bike       1085.2
524    SHP10524  2026-06-09     West          Road    Container       1164.4
562    SHP10562  2026-07-17    North           Air        Truck       1209.2
572    SHP10572  2026-07-27    South           Air        Truck       1271.4
590    SHP10590  2026-08-14    North           Air    Container       1271.9
601    SHP10601  2026-08-25    South          Road        Truck       1146.0
605    SHP10605  2026-08-29     East          Rail          Van       1061.9
623    SHP10623  2026-09-16     East          Ship         Bike       1082.0
655    SHP10655  2026-10-18    North          Ship        Truck       1419.4
672    SHP10672  2026-11-04    North          Ship    Container       1074.1
680    SHP10680  2026-11-12     West          Road        Truck       1290.6
686    SHP10686  2026-11-18     East          Ship        Truck       1144.2
696    SHP10696  2026-11-28    South          Road          Van      30000.0
698    SHP10698  2026-11-30    North          Ship    Container       1062.2
730    SHP10730  2027-01-01    North          Road    Container       1402.6
745    SHP10745  2027-01-16  Central          Road    Container       1941.1
756    SHP10756  2027-01-27     West          Ship          Van      30000.0
769    SHP10769  2027-02-09     West          Road          Van       1140.0
781    SHP10781  2027-02-21     East          Ship    Container      30000.0
858    SHP10858  2027-05-09    South          Ship        Truck       1040.1
884    SHP10884  2027-06-04     West          Road        Truck       1125.2
894    SHP10894  2027-06-14     West          Rail        Truck       1075.7

     Package_Weight_kg  Expected_Delivery_Days  Delivery_Days  \
7                 4.92                       6            6.5
65                3.27                       4            5.6
70               11.71                       4            4.8
84                4.36                       6            8.1
104              11.09                       7            8.9
109               4.50                       1            2.6
110               5.29                       4            3.8
121               6.54                       6            8.7
193               4.71                       4            5.4
202               9.27                       2            3.9
204               9.52                       1            3.2
225               3.27                       3            2.3
265               4.65                       2            2.6
294               7.60                       2            5.8
357               8.49                       1            2.2
457               2.51                       4            5.2
480              14.37                       4            5.6
498              14.08                       4            6.3
524               5.92                       3            2.4
562               6.96                       3            4.6
572               3.00                       3            4.5
590              12.36                       2            2.7
601               4.72                       3            4.7
605              11.47                       3            3.7
623               3.28                       5            5.1
655               3.50                       7           11.3
672              16.86                       4            5.5
680               8.91                       3            4.9
686               4.81                       6            7.0
696               1.56                       1            0.6
698               5.54                       5            7.1
730              13.96                       2            3.8
745               4.01                       4            8.3
756              20.25                       5            6.6
769              11.82                       5            6.3
781               4.08                       2            1.5
858               5.11                       6            7.4
884               3.71                       1            3.9
894               5.80                       5            6.6

     Shipping_Cost_INR  Delivery_Rating Weather Delivery_Status
7              1499.52              5.0   Clear         On Time
65             3678.05              3.2    Rain      In Transit
70             4224.15              4.5   Clear         On Time
84             4780.01              3.7   Clear       Cancelled
104            4035.07              4.0     Fog         Delayed
109            3460.01              3.8   Clear       Cancelled
110            8220.11              4.3   Clear         On Time
121            5082.03              4.3   Clear         On Time
193            5043.22              3.8   Clear      In Transit
202            4862.96              3.8   Clear       Cancelled
204            3715.78              4.3     Fog         On Time
225            2188.24              3.8   Clear         On Time
265            3775.36              3.6    Rain         On Time
294            7176.27              3.0   Clear         On Time
357            3255.58              3.1   Clear      In Transit
457            4960.94              3.9   Clear       Cancelled
480            3678.00              3.8     Fog         On Time
498            3972.44              4.4   Storm         On Time
524            3624.24              4.0     Fog         On Time
562            4013.67              3.5   Clear         On Time
572            3612.85              4.9     Fog         On Time
590            7280.48              2.6   Clear       Cancelled
601            4156.98              3.0   Clear         On Time
605            4117.61              4.2   Clear      In Transit
623            3980.97              5.0   Clear      In Transit
655            4160.67              3.8   Clear      In Transit
672            4274.85              4.1   Storm       Cancelled
680            4495.22              4.9   Clear         On Time
686            3147.09              3.9   Clear         On Time
696            1096.09              4.2   Clear         On Time
698            4090.23              3.9   Storm         On Time
730            4278.38              3.4   Clear         Delayed
745          250000.00              4.5   Clear         On Time
756            2352.97              4.7    Rain         On Time
769            5515.18              3.6    Rain         Delayed
781            4685.85              3.9   Clear         Delayed
858            3503.94              4.1    Rain       Cancelled
884            3993.54              4.2    Rain         On Time
894            3827.92              4.8   Clear         On Time

In [ ]:
data["Order_Date"] = pd.to_datetime(data["Order_Date"],errors="coerce"
)

In [103]:
data["Order_Year"] = data["Order_Date"].dt.year
data["Order_Month"] = data["Order_Date"].dt.month
data.head()

,Shipment_ID,Order_Date,Region,Shipping_Mode,Vehicle_Type,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating,Weather,Delivery_Status,Order_Year,Order_Month,Delivery_Delay_Days
0,SHP10000,2025-01-01,South,Road,Truck,679.9,4.87,2,3.4,4383.32,4.0,Clear,In Transit,2025,1,1.4
1,SHP10001,2025-01-02,Central,Rail,Truck,521.7,4.99,1,2.7,2514.35,3.7,Rain,Cancelled,2025,1,1.7
2,SHP10002,2025-01-03,West,Ship,Bike,740.9,9.20,7,8.2,7013.15,4.7,Clear,Delayed,2025,1,1.2
3,SHP10003,2025-01-04,East,Air,Truck,414.4,5.24,3,4.3,1564.63,4.1,Storm,In Transit,2025,1,1.3
4,SHP10004,2025-01-05,North,Ship,Truck,263.1,6.85,4,3.6,2593.65,4.0,Clear,On Time,2025,1,-0.4

In [104]:
data["Delivery_Delay_Days"] = ( data["Delivery_Days"]- data["Expected_Delivery_Days"])
data.head()

,Shipment_ID,Order_Date,Region,Shipping_Mode,Vehicle_Type,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating,Weather,Delivery_Status,Order_Year,Order_Month,Delivery_Delay_Days
0,SHP10000,2025-01-01,South,Road,Truck,679.9,4.87,2,3.4,4383.32,4.0,Clear,In Transit,2025,1,1.4
1,SHP10001,2025-01-02,Central,Rail,Truck,521.7,4.99,1,2.7,2514.35,3.7,Rain,Cancelled,2025,1,1.7
2,SHP10002,2025-01-03,West,Ship,Bike,740.9,9.20,7,8.2,7013.15,4.7,Clear,Delayed,2025,1,1.2
3,SHP10003,2025-01-04,East,Air,Truck,414.4,5.24,3,4.3,1564.63,4.1,Storm,In Transit,2025,1,1.3
4,SHP10004,2025-01-05,North,Ship,Truck,263.1,6.85,4,3.6,2593.65,4.0,Clear,On Time,2025,1,-0.4

In [108]:
data["Late_Flag"] = ( data["Delivery_Days"] > data["Expected_Delivery_Days"]).astype(int)
data.head()

,Shipment_ID,Order_Date,Region,Shipping_Mode,Vehicle_Type,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating,Weather,Delivery_Status,Order_Year,Order_Month,Delivery_Delay_Days,Late_Flag
0,SHP10000,2025-01-01,South,Road,Truck,679.9,4.87,2,3.4,4383.32,4.0,Clear,In Transit,2025,1,1.4,1
1,SHP10001,2025-01-02,Central,Rail,Truck,521.7,4.99,1,2.7,2514.35,3.7,Rain,Cancelled,2025,1,1.7,1
2,SHP10002,2025-01-03,West,Ship,Bike,740.9,9.20,7,8.2,7013.15,4.7,Clear,Delayed,2025,1,1.2,1
3,SHP10003,2025-01-04,East,Air,Truck,414.4,5.24,3,4.3,1564.63,4.1,Storm,In Transit,2025,1,1.3,1
4,SHP10004,2025-01-05,North,Ship,Truck,263.1,6.85,4,3.6,2593.65,4.0,Clear,On Time,2025,1,-0.4,0

In [110]:
columns = [
    "Distance_km",
    "Package_Weight_kg",
    "Shipping_Cost_INR",
    "Delivery_Days"
]

for col in columns:
    data[col + "_Normalized"] = ((data[col] - data[col].min()) /(data[col].max() - data[col].min()))

In [113]:
print("Shape:", data.shape)

print("Missing Values:",data.isnull().sum().sum())

print("Duplicate Rows:",data.duplicated().sum())

Shape: (1000, 21)
Missing Values: 0
Duplicate Rows: 0

In [115]:
data.describe()

,Order_Date,Distance_km,Package_Weight_kg,Expected_Delivery_Days,Delivery_Days,Shipping_Cost_INR,Delivery_Rating,Order_Year,Order_Month,Delivery_Delay_Days,Late_Flag,Distance_km_Normalized,Package_Weight_kg_Normalized,Shipping_Cost_INR_Normalized,Delivery_Days_Normalized
count,1000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,2026-05-15 12:00:00,602.810443,10.358230,3.458000,4.088800,4562.674220,3.984400,2025.905000,6.107000,0.630800,0.714000,0.013005,0.012182,0.004858,0.332296
min,2025-01-01 00:00:00,17.800000,0.620000,1.000000,0.500000,679.220000,2.200000,2025.000000,1.000000,-2.600000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2025-09-07 18:00:00,219.950000,4.390000,2.000000,2.700000,1879.155000,3.600000,2025.000000,3.000000,-0.100000,0.000000,0.004494,0.004716,0.001501,0.203704
50%,2026-05-15 12:00:00,365.700000,7.060000,3.000000,4.000000,2511.745000,4.000000,2026.000000,6.000000,0.600000,1.000000,0.007734,0.008056,0.002293,0.324074
75%,2027-01-20 06:00:00,547.225000,11.100000,4.250000,5.300000,3248.820000,4.400000,2027.000000,9.000000,1.300000,1.000000,0.011770,0.013110,0.003215,0.444444
max,2027-09-27 00:00:00,45000.000000,800.000000,7.000000,11.300000,800000.000000,5.000000,2027.000000,12.000000,4.400000,1.000000,1.000000,1.000000,1.000000,1.000000
std,NaN,2422.796995,35.820242,1.586428,1.900186,32612.984219,0.594685,0.791582,3.306128,1.064615,0.452115,0.053861,0.044810,0.040801,0.175943

In [117]:
data.to_csv("logistics_cleaned_data.csv",index=False)